In [1]:
import torch

In [22]:
x1 = torch.empty(5, 3) # 未初始化
x2 = torch.rand(3, 3)
x3 = torch.zeros(5, 3, dtype=torch.long)
x4 = torch.ones(5,3,requires_grad=True)
x5 = torch.linspace(0,1,10)

x6 = x3 + x4
print(x6)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<AddBackward0>)


In [ ]:
print(x6.clone().view(15))
print(x2.svd())

In [15]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones(5, 3, device=device)
    y1 = x6.to(device)
    print(y)
    print(y1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [28]:
x = torch.linspace(1, 4, 4, requires_grad=True)
y = 2 * x
z = y.view(2,2)
print(z)
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)
tensor([2.0000, 0.2000, 0.0200, 0.0020])
